[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['echo "No build step needed"']

[start]
cmd = 'cd backend && node src/index.js'
